---
title: "Work-from-home and network of innovation"
format: 
  clean-revealjs:
    self-contained: true
    smaller: true
    slide-number: c
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
author:
  - name: Hyoungchul Kim
    affiliations: Wharton UPenn
date: last-modified
bibliography: refs.bib
---

## Motivation

#### Work-From-Home (wfh) is a prevalent form of working arrangement

- @bloom, @barrero, @criscuolo, @aksoy, @galasso, @brynjolfsson

#### Geographic proximity is important in innovation

- Collaboration at a distance is especially challenging in the early stages of research (@lin-frey-wu).

- wfh can lead to slower pace of innovation, negatively affecting the productivity of the firm.

#### But wfh also has benefits that can boost innovation

- Spread of internet connectivity can lead to increased knowledge flow across locations and higher patenting activity (@chen-frey-presidente, @forman-van1, @forman-van2)

- This is because... (@barrero2)
  + There is opportunity cost to chatting with your coworker in the next-door office.
  + Remote-collaboration tech expand the opportunities to form teams that are optimized for particular research projects and questions.

## Research question

####

Geographical location of innovation important. How is WFH changing this network of innovation? WFH also allowed rise of contactless communication. Did this lessen the impact of geographical importance of innovation?

## Data overview

#### For US

- **PatentsView** (Universe of patents produced between 1976 to 2022).
- Link patent assignees to the universe of firms in the restricted **US Longitudinal Business Database (LBS)**.

#### For Korea

- **Establishment data**: South Korea has a data that has universe of the location of establishments and can link them around 2007.
- **Innovation data**: I have a data on all the patents and the location of innovators that made such patents from 2000.

#### Occupation data

- Maybe use data such as America community survey to see the distribution of the occupation of people in the region.

- We can get similar data in South Korea as well.

## Reduced-form Method

I am not sure how to construct a right regression.

- For treatment variation, I am trying to sth similar to @dingel-neiman:
  + Use occupation data before COVID-19 to check eligibility level for WFH in each region.
  + Use this variation and apply DiD method (using COVID-19 as sort of exogenous shock).

- But I am not yet sure how I should construct my dependent variable to examine my research question.
  + I am trying to understand how WFH disrupts? or changes the network structure of innvoation.

- Some possibility: WFH kinds of widens the choice set for inventors and the firm. Maybe some outsourcing behavior of innovation for firms?

## Structural model

Maybe some discrete choice model of firms when choosing inventors to connect or hire? WFH would mean change in the level of connection cost.

## References

::: {#refs}
:::
